version: '3.7'

services:
  postgres:
    image: postgres:alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - '5432'

  server:
    build: .
    container_name: cars-api
    depends_on:
      - postgres
    restart: always
    tty: true
    environment:
      POSTGRES_HOST: postgres
    env_file: .env
    expose:
      - 8080
    ports:
      - '8080:8080'

volumes:
  pg_data:
